// <auto-generated />
namespace QuizApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class required_Adding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(required_Adding));
        
        string IMigrationMetadata.Id
        {
            get { return "202303021741209_required_Adding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
